all:
  hosts:
  children:
    vm_servers:
      hosts:
        192.168.0.101
      vars:
        ansible_user: god
    vm_desktops:
      hosts:
        192.168.0.104
      vars:
        ansible_user: god
