---
- name: Установка Docker
  become: true
  block:
    - name: Добавляем репозиторий
      ansible.builtin.apt_repository:
        repo: deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main
        state: present

    - name: Установка дополнительных пакетов для Docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: true
        cache_valid_time: 86400

    - name: Добавление ключа Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker.asc
        mode: 644

    - name: Установка стабильного репозитория
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Установка Docker-ce and Docker-compose plugin
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: Проверка установки Docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

- name: Завершение установки
  become: true
  block:
    - name: Добавление пользователя в группу Docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Перезагрузка
      ansible.builtin.reboot:
